version: "3.7"

services:

    app:
        image: node:14.17.0-alpine
        working_dir: /app
        volumes:
            - ./app:/app
        command: npm run start
        ports:
            - 3000:3000
        networks:
            - frontend
        depends_on:
            - api

    api:
        image: node:14.17.0-alpine
        working_dir: /api
        volumes:
            - ./api:/api
        command: npm run start
        ports:
            - 8000:8000
        networks:
            - backend
        depends_on:
            - database

    database:
        image: postgres:alpine
        volumes:
            - base_db:/var/lib/postgresql/data/
        ports:
            - 5432:5432
        networks:
            - backend
        env_file:
            - ./postgresql/.env

    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        networks:
            - frontend
            - backend
        depends_on:
            - api

volumes:
    base_db: {}

networks:
    frontend:
    backend: